---
language: python

services:
  - docker

env:
  - OS_VERSION=7
  - OS_VERSION=6

before_install:
  - sudo docker pull centos:${OS_VERSION}

install:
  - sudo docker run --detach --volume="${PWD}":/etc/ansible/roles/phabricator:ro --name centos-${OS_VERSION} centos:${OS_VERSION} sleep 300
  - sudo docker exec centos-${OS_VERSION} yum -y install epel-release
  - sudo docker exec centos-${OS_VERSION} yum -y install ansible
  - sudo docker exec centos-${OS_VERSION} ansible-galaxy install pcextreme.mariadb
  - sudo docker exec centos-${OS_VERSION} ansible-galaxy install geerlingguy.nginx

script:
  # Check syntax of ansible playbook
  - sudo docker exec centos-${OS_VERSION} ansible-playbook /etc/ansible/roles/phabricator/tests/test.yml --syntax-check
  # Run ansible playbook
  - sudo docker exec centos-${OS_VERSION} ansible-playbook /etc/ansible/roles/phabricator/tests/test.yml

after_script:
  - sudo docker stop centos-${OS_VERSION}

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
